# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    Esit\Databaselayer\Classes\Services\Helper\AbstractHelper:

    Esit\Databaselayer\Classes\Services\Helper\ConnectionHelper:

    Esit\Databaselayer\Classes\Services\Helper\DatabaseHelper:
        public: true

    Esit\Databaselayer\Classes\Services\Helper\DataHelper:

    Esit\Databaselayer\Classes\Services\Helper\QueryHelper:

    Esit\Databaselayer\Classes\Services\Helper\SchemaHelper:

    Esit\Databaselayer\Classes\Services\Helper\StatementHelper:
